# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Home Site for Projects and CS related Articles/Write ups
tagline:          'Tech Projects and Programming Content'
description:      'This is a page to consolidate my tech projects and to write-up about Programming concepts/algorithms and problems.'
url:              https://mrichards01.github.io/ProjectsSite/
baseurl:          /

author:
  name:           'Mark Richards'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/mrichards01/ProjectsSite
